import type { UpgradeDefinition } from '../types/game'

export const upgradeDefinitions = [
  {
    id: 'fiveS',
    name: '5S',
    summary: 'Células limpas reduzem defeitos e aceleram o fluxo.',
    category: 'quality',
    baseCost: 50,
    effectLabel: '-5% defeitos, +10% veloc.',
    maxLevel: 5,
    accent: 'green',
  },
  {
    id: 'kanban',
    name: 'Kanban',
    summary: 'Sinais puxados mantêm peças no tempo certo.',
    category: 'automation',
    baseCost: 200,
    effectLabel: '+20% veloc.',
    maxLevel: 5,
    accent: 'yellow',
  },
  {
    id: 'pokaYoke',
    name: 'Poka-Yoke',
    summary: 'À prova de erro detecta falhas cedo.',
    category: 'quality',
    baseCost: 500,
    effectLabel: '-15% defeitos',
    maxLevel: 5,
    accent: 'green',
  },
  {
    id: 'tpm',
    name: 'TPM',
    summary: 'Rotinas de manutenção elevam OEE e reduzem defeitos.',
    category: 'quality',
    baseCost: 1500,
    effectLabel: '+15% OEE, -10% defeitos',
    maxLevel: 5,
    accent: 'steel',
  },
  {
    id: 'andon',
    name: 'Andon',
    summary: 'Sinaliza paradas e recupera a linha automaticamente.',
    category: 'automation',
    baseCost: 4000,
    effectLabel: 'Recuperação auto., menos paradas',
    maxLevel: 5,
    accent: 'yellow',
  },
  {
    id: 'jidoka',
    name: 'Jidoka',
    summary: 'Para a linha para proteger qualidade, reduzindo ritmo.',
    category: 'quality',
    baseCost: 7500,
    effectLabel: '-40% defeitos, -10% veloc.',
    maxLevel: 5,
    accent: 'red',
  },
  {
    id: 'heijunka',
    name: 'Heijunka',
    summary: 'Nivela a produção e suaviza oscilações.',
    category: 'team',
    baseCost: 10000,
    effectLabel: '+25% OEE, menos variação',
    maxLevel: 5,
    accent: 'green',
  },
  {
    id: 'justInTime',
    name: 'Just-In-Time',
    summary: 'Acelera só quando a qualidade está sob controle.',
    category: 'automation',
    baseCost: 25000,
    effectLabel: '+50% veloc. se defeitos <5%',
    maxLevel: 5,
    accent: 'yellow',
  },
] satisfies readonly UpgradeDefinition[]
