import type { UpgradeDefinition } from '../types/game'

export const upgradeDefinitions = [
  {
    id: 'handPress',
    name: 'Hand Press',
    summary: 'Sharper manual workstations for every tap.',
    category: 'manual',
    baseCost: 15,
    baseOutput: 0.2,
    costMultiplier: 1.18,
    accent: 'green',
  },
  {
    id: 'beltTuner',
    name: 'Belt Tuner',
    summary: 'Smoother rollers keep parts moving.',
    category: 'automation',
    baseCost: 45,
    baseOutput: 0.8,
    costMultiplier: 1.22,
    accent: 'yellow',
  },
  {
    id: 'kanbanRack',
    name: 'Kanban Rack',
    summary: 'Tiny batch signals reduce idle gaps.',
    category: 'quality',
    baseCost: 120,
    baseOutput: 2.4,
    costMultiplier: 1.24,
    accent: 'green',
  },
  {
    id: 'qualityLoop',
    name: 'Quality Loop',
    summary: 'Quick checks turn rework into rhythm.',
    category: 'quality',
    baseCost: 360,
    baseOutput: 7.5,
    costMultiplier: 1.27,
    accent: 'steel',
  },
  {
    id: 'microFoundry',
    name: 'Micro Foundry',
    summary: 'Warm tooling for compact high-value runs.',
    category: 'automation',
    baseCost: 900,
    baseOutput: 18,
    costMultiplier: 1.3,
    accent: 'yellow',
  },
  {
    id: 'shiftCrew',
    name: 'Shift Crew',
    summary: 'A focused crew keeps improvements compounding.',
    category: 'team',
    baseCost: 2200,
    baseOutput: 42,
    costMultiplier: 1.34,
    accent: 'green',
  },
] satisfies readonly UpgradeDefinition[]
