import { describe, expect, it } from 'vitest'
import { makePersistedGameState } from '../../test/makePersistedGameState'
import { createSaveEnvelope, parseSaveEnvelope } from './integrity'

describe('save integrity envelope', () => {
  it('accepts a save generated by the app', () => {
    const state = makePersistedGameState({ points: 300, savedAt: 1_000 })
    const envelope = createSaveEnvelope(state)

    expect(parseSaveEnvelope(JSON.stringify(envelope))).toEqual({
      issue: null,
      state,
    })
  })

  it('detects a manual localStorage point edit by checksum mismatch', () => {
    const state = makePersistedGameState({ points: 300, savedAt: 1_000 })
    const envelope = createSaveEnvelope(state)
    const tamperedEnvelope = {
      ...envelope,
      state: { ...envelope.state, points: 900 },
    }

    expect(parseSaveEnvelope(JSON.stringify(tamperedEnvelope))).toEqual({
      issue: 'checksum',
      state: null,
    })
  })

  it('rejects corrupted JSON and unexpected formats', () => {
    expect(parseSaveEnvelope('{')).toEqual({
      issue: 'corrupted',
      state: null,
    })
    expect(parseSaveEnvelope(JSON.stringify({ points: 300 }))).toEqual({
      issue: 'invalid-format',
      state: null,
    })
  })
})
